---
all:
  children:
    provider:
      children:
        p:
          hosts:
            P1: {ansible_host: 10.201.255.101}
            P2: {ansible_host: 10.201.255.102}
            P3: {ansible_host: 10.201.255.103}
            P4: {ansible_host: 10.201.255.104}
            P5: {ansible_host: 10.201.255.105}
            P6: {ansible_host: 10.201.255.106}
            P7: {ansible_host: 10.201.255.107}
            P8: {ansible_host: 10.201.255.108}
        pe:
          hosts:
            PE1: {ansible_host: 10.201.255.111}
            PE2: {ansible_host: 10.201.255.112}
            PE3: {ansible_host: 10.201.255.113}
            PE4: {ansible_host: 10.201.255.114}
            PE5: {ansible_host: 10.201.255.115}
            PE6: {ansible_host: 10.201.255.116}
            PE7: {ansible_host: 10.201.255.117}
            PE8: {ansible_host: 10.201.255.118}
        rr:
          hosts:
            RR1: {ansible_host: 10.201.255.121}
            RR2: {ansible_host: 10.201.255.122}
      vars:
        ansible_connection: ansible.netcommon.network_cli
        ansible_network_os: cisco.iosxr.iosxr
        ansible_user: "{{ lookup('ansible.builtin.env', 'CCIE_XRD_USERNAME', default='clab') }}"
        ansible_password: "{{ lookup('ansible.builtin.env', 'CCIE_XRD_PASSWORD', default=undef()) }}"
        ansible_command_timeout: 60
        ansible_host_key_checking: false
    customer:
      hosts:
        CE1: {ansible_host: 10.201.255.131}
        CE2: {ansible_host: 10.201.255.132}
        CE3: {ansible_host: 10.201.255.133}
        CE4: {ansible_host: 10.201.255.134}
        CE5: {ansible_host: 10.201.255.135}
        CE6: {ansible_host: 10.201.255.136}
        CE7: {ansible_host: 10.201.255.137}
        CE8: {ansible_host: 10.201.255.138}
        CE9: {ansible_host: 10.201.255.139}
        C1: {ansible_host: 10.201.255.141}
        C2: {ansible_host: 10.201.255.142}
      vars:
        ansible_connection: ansible.netcommon.network_cli
        ansible_network_os: cisco.ios.ios
        ansible_user: "{{ lookup('ansible.builtin.env', 'CCIE_IOL_USERNAME', default='admin') }}"
        ansible_password: "{{ lookup('ansible.builtin.env', 'CCIE_IOL_PASSWORD', default=undef()) }}"
